# Generated by Django 5.2.3 on 2026-03-01 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_alter_blog_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='creted_at',
            new_name='created_at',
        ),
    ]
